---
- name: Copy backup script
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/scripts/backup.sh"
    dest: /opt/ais-coursework/scripts/backup.sh
    mode: '0755'

- name: Copy restore script placeholder
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/scripts/restore.sh"
    dest: /opt/ais-coursework/scripts/restore.sh
    mode: '0755'

- name: Ensure backups directory exists
  ansible.builtin.file:
    path: /opt/ais-coursework/backups
    state: directory
    mode: '0750'
